# Generated by Django 4.2.5 on 2023-10-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runningApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestop',
            options={'ordering': ['stop_order']},
        ),
    ]
