# Generated by Django 4.2.5 on 2023-11-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runningApp', '0002_alter_routestop_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='route',
            name='gradient_range',
            field=models.FloatField(default=0.0),
        ),
    ]
