name: Run Mock Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            print("Working directory:", os.getcwd())
            print("Files:", os.listdir("."))
            from runningApp.test_mock_tests import *
            unittest.main()
